spring:
  application:
    name: eureka-server-vending-app
  config:
    import: optional:configserver:http://localhost:9090/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8090